### ISSUE TITLE
Bamboo-Server: Move download of Bamboo to Dockerfile

### ISSUE THREAD

**Issue by andreas-mausch** [hwuethrich/docker-images#16]
Hi Hannes,

first of all thanks for your effort to create the image.

What is the reason to download and extract Bamboo each time I start the container?
Wouldn't it make sense to move this step to the Dockerfile?

This would result in improved startup time and I could specify the Bamboo version like this:
hwuethrich/bamboo-server:5.7.2

Andreas

**Comment by hwuethrich** [comment]
Hi Andreas. When I first created the image, I wasn't sure about the legal implications if I bundle the server in the image. Therefore it downloads Bamboo server from Atlassian website on the first run. Also, I didn't have to rebuild the image every time a version came out. But as you pointed out, it also has its disadvantages... 

But because I switched jobs and am currently not using these images anymore, I'm probably not going to change it. PRs welcome, though! ;)
